// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BittrexHistoricData  string
	Data                 string
	PoloniexHistoricData string
	Posdatatable         string
	Powdatatable         string
}{
	BittrexHistoricData:  "bittrex_historic_data",
	Data:                 "data",
	PoloniexHistoricData: "poloniex_historic_data",
	Posdatatable:         "posdatatable",
	Powdatatable:         "powdatatable",
}
