// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

var TableNames = struct {
	ChartData    string
	HistoricData string
	PosData      string
	PowData      string
}{
	ChartData:    "chart_data",
	HistoricData: "historic_data",
	PosData:      "pos_data",
	PowData:      "pow_data",
}
