// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"gopkg.in/nullbio/null.v6"
)

// EventOne is an object representing the database table.
type EventOne struct {
	ID   int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	Day  string      `boil:"day" json:"day" toml:"day" yaml:"day"`

	R *eventOneR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L eventOneL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EventOneColumns = struct {
	ID   string
	Name string
	Day  string
}{
	ID:   "id",
	Name: "name",
	Day:  "day",
}

// eventOneR is where relationships are stored.
type eventOneR struct {
}

// eventOneL is where Load methods for each relationship are stored.
type eventOneL struct{}

var (
	eventOneColumns               = []string{"id", "name", "day"}
	eventOneColumnsWithoutDefault = []string{"name", "day"}
	eventOneColumnsWithDefault    = []string{"id"}
	eventOnePrimaryKeyColumns     = []string{"id"}
)

type (
	// EventOneSlice is an alias for a slice of pointers to EventOne.
	// This should generally be used opposed to []EventOne.
	EventOneSlice []*EventOne
	// EventOneHook is the signature for custom EventOne hook methods
	EventOneHook func(boil.Executor, *EventOne) error

	eventOneQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	eventOneType                 = reflect.TypeOf(&EventOne{})
	eventOneMapping              = queries.MakeStructMapping(eventOneType)
	eventOnePrimaryKeyMapping, _ = queries.BindMapping(eventOneType, eventOneMapping, eventOnePrimaryKeyColumns)
	eventOneInsertCacheMut       sync.RWMutex
	eventOneInsertCache          = make(map[string]insertCache)
	eventOneUpdateCacheMut       sync.RWMutex
	eventOneUpdateCache          = make(map[string]updateCache)
	eventOneUpsertCacheMut       sync.RWMutex
	eventOneUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var eventOneBeforeInsertHooks []EventOneHook
var eventOneBeforeUpdateHooks []EventOneHook
var eventOneBeforeDeleteHooks []EventOneHook
var eventOneBeforeUpsertHooks []EventOneHook

var eventOneAfterInsertHooks []EventOneHook
var eventOneAfterSelectHooks []EventOneHook
var eventOneAfterUpdateHooks []EventOneHook
var eventOneAfterDeleteHooks []EventOneHook
var eventOneAfterUpsertHooks []EventOneHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EventOne) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range eventOneBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EventOne) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range eventOneBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EventOne) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range eventOneBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EventOne) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range eventOneBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EventOne) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range eventOneAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EventOne) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range eventOneAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EventOne) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range eventOneAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EventOne) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range eventOneAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EventOne) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range eventOneAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEventOneHook registers your hook function for all future operations.
func AddEventOneHook(hookPoint boil.HookPoint, eventOneHook EventOneHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		eventOneBeforeInsertHooks = append(eventOneBeforeInsertHooks, eventOneHook)
	case boil.BeforeUpdateHook:
		eventOneBeforeUpdateHooks = append(eventOneBeforeUpdateHooks, eventOneHook)
	case boil.BeforeDeleteHook:
		eventOneBeforeDeleteHooks = append(eventOneBeforeDeleteHooks, eventOneHook)
	case boil.BeforeUpsertHook:
		eventOneBeforeUpsertHooks = append(eventOneBeforeUpsertHooks, eventOneHook)
	case boil.AfterInsertHook:
		eventOneAfterInsertHooks = append(eventOneAfterInsertHooks, eventOneHook)
	case boil.AfterSelectHook:
		eventOneAfterSelectHooks = append(eventOneAfterSelectHooks, eventOneHook)
	case boil.AfterUpdateHook:
		eventOneAfterUpdateHooks = append(eventOneAfterUpdateHooks, eventOneHook)
	case boil.AfterDeleteHook:
		eventOneAfterDeleteHooks = append(eventOneAfterDeleteHooks, eventOneHook)
	case boil.AfterUpsertHook:
		eventOneAfterUpsertHooks = append(eventOneAfterUpsertHooks, eventOneHook)
	}
}

// OneP returns a single eventOne record from the query, and panics on error.
func (q eventOneQuery) OneP() *EventOne {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single eventOne record from the query.
func (q eventOneQuery) One() (*EventOne, error) {
	o := &EventOne{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for event_one")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all EventOne records from the query, and panics on error.
func (q eventOneQuery) AllP() EventOneSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all EventOne records from the query.
func (q eventOneQuery) All() (EventOneSlice, error) {
	var o []*EventOne

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EventOne slice")
	}

	if len(eventOneAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all EventOne records in the query, and panics on error.
func (q eventOneQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all EventOne records in the query.
func (q eventOneQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count event_one rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q eventOneQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q eventOneQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if event_one exists")
	}

	return count > 0, nil
}

// EventOnesG retrieves all records.
func EventOnesG(mods ...qm.QueryMod) eventOneQuery {
	return EventOnes(boil.GetDB(), mods...)
}

// EventOnes retrieves all the records using an executor.
func EventOnes(exec boil.Executor, mods ...qm.QueryMod) eventOneQuery {
	mods = append(mods, qm.From("\"event_one\""))
	return eventOneQuery{NewQuery(exec, mods...)}
}

// FindEventOneG retrieves a single record by ID.
func FindEventOneG(id int, selectCols ...string) (*EventOne, error) {
	return FindEventOne(boil.GetDB(), id, selectCols...)
}

// FindEventOneGP retrieves a single record by ID, and panics on error.
func FindEventOneGP(id int, selectCols ...string) *EventOne {
	retobj, err := FindEventOne(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindEventOne retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEventOne(exec boil.Executor, id int, selectCols ...string) (*EventOne, error) {
	eventOneObj := &EventOne{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"event_one\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(eventOneObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from event_one")
	}

	return eventOneObj, nil
}

// FindEventOneP retrieves a single record by ID with an executor, and panics on error.
func FindEventOneP(exec boil.Executor, id int, selectCols ...string) *EventOne {
	retobj, err := FindEventOne(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *EventOne) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *EventOne) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *EventOne) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *EventOne) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no event_one provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventOneColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	eventOneInsertCacheMut.RLock()
	cache, cached := eventOneInsertCache[key]
	eventOneInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			eventOneColumns,
			eventOneColumnsWithDefault,
			eventOneColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(eventOneType, eventOneMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(eventOneType, eventOneMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"event_one\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"event_one\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into event_one")
	}

	if !cached {
		eventOneInsertCacheMut.Lock()
		eventOneInsertCache[key] = cache
		eventOneInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single EventOne record. See Update for
// whitelist behavior description.
func (o *EventOne) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single EventOne record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *EventOne) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the EventOne, and panics on error.
// See Update for whitelist behavior description.
func (o *EventOne) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the EventOne.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *EventOne) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	eventOneUpdateCacheMut.RLock()
	cache, cached := eventOneUpdateCache[key]
	eventOneUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			eventOneColumns,
			eventOnePrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update event_one, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"event_one\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, eventOnePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(eventOneType, eventOneMapping, append(wl, eventOnePrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update event_one row")
	}

	if !cached {
		eventOneUpdateCacheMut.Lock()
		eventOneUpdateCache[key] = cache
		eventOneUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q eventOneQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q eventOneQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for event_one")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o EventOneSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o EventOneSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o EventOneSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EventOneSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventOnePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"event_one\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, eventOnePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in eventOne slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *EventOne) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *EventOne) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *EventOne) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *EventOne) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no event_one provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventOneColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	eventOneUpsertCacheMut.RLock()
	cache, cached := eventOneUpsertCache[key]
	eventOneUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			eventOneColumns,
			eventOneColumnsWithDefault,
			eventOneColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			eventOneColumns,
			eventOnePrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert event_one, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(eventOnePrimaryKeyColumns))
			copy(conflict, eventOnePrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"event_one\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(eventOneType, eventOneMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(eventOneType, eventOneMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert event_one")
	}

	if !cached {
		eventOneUpsertCacheMut.Lock()
		eventOneUpsertCache[key] = cache
		eventOneUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single EventOne record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *EventOne) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single EventOne record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *EventOne) DeleteG() error {
	if o == nil {
		return errors.New("models: no EventOne provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single EventOne record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *EventOne) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single EventOne record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EventOne) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no EventOne provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), eventOnePrimaryKeyMapping)
	sql := "DELETE FROM \"event_one\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from event_one")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q eventOneQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q eventOneQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no eventOneQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from event_one")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o EventOneSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o EventOneSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no EventOne slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o EventOneSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EventOneSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no EventOne slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(eventOneBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventOnePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"event_one\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, eventOnePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from eventOne slice")
	}

	if len(eventOneAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *EventOne) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *EventOne) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *EventOne) ReloadG() error {
	if o == nil {
		return errors.New("models: no EventOne provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EventOne) Reload(exec boil.Executor) error {
	ret, err := FindEventOne(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *EventOneSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *EventOneSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EventOneSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty EventOneSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EventOneSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	eventOnes := EventOneSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventOnePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"event_one\".* FROM \"event_one\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, eventOnePrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&eventOnes)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EventOneSlice")
	}

	*o = eventOnes

	return nil
}

// EventOneExists checks if the EventOne row exists.
func EventOneExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"event_one\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if event_one exists")
	}

	return exists, nil
}

// EventOneExistsG checks if the EventOne row exists.
func EventOneExistsG(id int) (bool, error) {
	return EventOneExists(boil.GetDB(), id)
}

// EventOneExistsGP checks if the EventOne row exists. Panics on error.
func EventOneExistsGP(id int) bool {
	e, err := EventOneExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// EventOneExistsP checks if the EventOne row exists. Panics on error.
func EventOneExistsP(exec boil.Executor, id int) bool {
	e, err := EventOneExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
