// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"gopkg.in/nullbio/null.v6"
)

// HistoricDatum is an object representing the database table.
type HistoricDatum struct {
	ID            int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Exchangeid    null.Int    `boil:"exchangeid" json:"exchangeid,omitempty" toml:"exchangeid" yaml:"exchangeid,omitempty"`
	Globaltradeid null.String `boil:"globaltradeid" json:"globaltradeid,omitempty" toml:"globaltradeid" yaml:"globaltradeid,omitempty"`
	Tradeid       null.String `boil:"tradeid" json:"tradeid,omitempty" toml:"tradeid" yaml:"tradeid,omitempty"`
	Timest        null.Time   `boil:"timest" json:"timest,omitempty" toml:"timest" yaml:"timest,omitempty"`
	Quantity      null.String `boil:"quantity" json:"quantity,omitempty" toml:"quantity" yaml:"quantity,omitempty"`
	Price         null.String `boil:"price" json:"price,omitempty" toml:"price" yaml:"price,omitempty"`
	Total         null.String `boil:"total" json:"total,omitempty" toml:"total" yaml:"total,omitempty"`
	FillType      null.String `boil:"fill_type" json:"fill_type,omitempty" toml:"fill_type" yaml:"fill_type,omitempty"`
	OrderType     null.String `boil:"order_type" json:"order_type,omitempty" toml:"order_type" yaml:"order_type,omitempty"`

	R *historicDatumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L historicDatumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var HistoricDatumColumns = struct {
	ID            string
	Exchangeid    string
	Globaltradeid string
	Tradeid       string
	Timest        string
	Quantity      string
	Price         string
	Total         string
	FillType      string
	OrderType     string
}{
	ID:            "id",
	Exchangeid:    "exchangeid",
	Globaltradeid: "globaltradeid",
	Tradeid:       "tradeid",
	Timest:        "timest",
	Quantity:      "quantity",
	Price:         "price",
	Total:         "total",
	FillType:      "fill_type",
	OrderType:     "order_type",
}

// historicDatumR is where relationships are stored.
type historicDatumR struct {
}

// historicDatumL is where Load methods for each relationship are stored.
type historicDatumL struct{}

var (
	historicDatumColumns               = []string{"id", "exchangeid", "globaltradeid", "tradeid", "timest", "quantity", "price", "total", "fill_type", "order_type"}
	historicDatumColumnsWithoutDefault = []string{"exchangeid", "globaltradeid", "tradeid", "timest", "quantity", "price", "total", "fill_type", "order_type"}
	historicDatumColumnsWithDefault    = []string{"id"}
	historicDatumPrimaryKeyColumns     = []string{"id"}
)

type (
	// HistoricDatumSlice is an alias for a slice of pointers to HistoricDatum.
	// This should generally be used opposed to []HistoricDatum.
	HistoricDatumSlice []*HistoricDatum
	// HistoricDatumHook is the signature for custom HistoricDatum hook methods
	HistoricDatumHook func(boil.Executor, *HistoricDatum) error

	historicDatumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	historicDatumType                 = reflect.TypeOf(&HistoricDatum{})
	historicDatumMapping              = queries.MakeStructMapping(historicDatumType)
	historicDatumPrimaryKeyMapping, _ = queries.BindMapping(historicDatumType, historicDatumMapping, historicDatumPrimaryKeyColumns)
	historicDatumInsertCacheMut       sync.RWMutex
	historicDatumInsertCache          = make(map[string]insertCache)
	historicDatumUpdateCacheMut       sync.RWMutex
	historicDatumUpdateCache          = make(map[string]updateCache)
	historicDatumUpsertCacheMut       sync.RWMutex
	historicDatumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var historicDatumBeforeInsertHooks []HistoricDatumHook
var historicDatumBeforeUpdateHooks []HistoricDatumHook
var historicDatumBeforeDeleteHooks []HistoricDatumHook
var historicDatumBeforeUpsertHooks []HistoricDatumHook

var historicDatumAfterInsertHooks []HistoricDatumHook
var historicDatumAfterSelectHooks []HistoricDatumHook
var historicDatumAfterUpdateHooks []HistoricDatumHook
var historicDatumAfterDeleteHooks []HistoricDatumHook
var historicDatumAfterUpsertHooks []HistoricDatumHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *HistoricDatum) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range historicDatumBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *HistoricDatum) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range historicDatumBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *HistoricDatum) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range historicDatumBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *HistoricDatum) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range historicDatumBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *HistoricDatum) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range historicDatumAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *HistoricDatum) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range historicDatumAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *HistoricDatum) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range historicDatumAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *HistoricDatum) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range historicDatumAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *HistoricDatum) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range historicDatumAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddHistoricDatumHook registers your hook function for all future operations.
func AddHistoricDatumHook(hookPoint boil.HookPoint, historicDatumHook HistoricDatumHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		historicDatumBeforeInsertHooks = append(historicDatumBeforeInsertHooks, historicDatumHook)
	case boil.BeforeUpdateHook:
		historicDatumBeforeUpdateHooks = append(historicDatumBeforeUpdateHooks, historicDatumHook)
	case boil.BeforeDeleteHook:
		historicDatumBeforeDeleteHooks = append(historicDatumBeforeDeleteHooks, historicDatumHook)
	case boil.BeforeUpsertHook:
		historicDatumBeforeUpsertHooks = append(historicDatumBeforeUpsertHooks, historicDatumHook)
	case boil.AfterInsertHook:
		historicDatumAfterInsertHooks = append(historicDatumAfterInsertHooks, historicDatumHook)
	case boil.AfterSelectHook:
		historicDatumAfterSelectHooks = append(historicDatumAfterSelectHooks, historicDatumHook)
	case boil.AfterUpdateHook:
		historicDatumAfterUpdateHooks = append(historicDatumAfterUpdateHooks, historicDatumHook)
	case boil.AfterDeleteHook:
		historicDatumAfterDeleteHooks = append(historicDatumAfterDeleteHooks, historicDatumHook)
	case boil.AfterUpsertHook:
		historicDatumAfterUpsertHooks = append(historicDatumAfterUpsertHooks, historicDatumHook)
	}
}

// OneP returns a single historicDatum record from the query, and panics on error.
func (q historicDatumQuery) OneP() *HistoricDatum {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single historicDatum record from the query.
func (q historicDatumQuery) One() (*HistoricDatum, error) {
	o := &HistoricDatum{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for historic_data")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all HistoricDatum records from the query, and panics on error.
func (q historicDatumQuery) AllP() HistoricDatumSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all HistoricDatum records from the query.
func (q historicDatumQuery) All() (HistoricDatumSlice, error) {
	var o []*HistoricDatum

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to HistoricDatum slice")
	}

	if len(historicDatumAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all HistoricDatum records in the query, and panics on error.
func (q historicDatumQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all HistoricDatum records in the query.
func (q historicDatumQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count historic_data rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q historicDatumQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q historicDatumQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if historic_data exists")
	}

	return count > 0, nil
}

// HistoricDataG retrieves all records.
func HistoricDataG(mods ...qm.QueryMod) historicDatumQuery {
	return HistoricData(boil.GetDB(), mods...)
}

// HistoricData retrieves all the records using an executor.
func HistoricData(exec boil.Executor, mods ...qm.QueryMod) historicDatumQuery {
	mods = append(mods, qm.From("\"historic_data\""))
	return historicDatumQuery{NewQuery(exec, mods...)}
}

// FindHistoricDatumG retrieves a single record by ID.
func FindHistoricDatumG(id int, selectCols ...string) (*HistoricDatum, error) {
	return FindHistoricDatum(boil.GetDB(), id, selectCols...)
}

// FindHistoricDatumGP retrieves a single record by ID, and panics on error.
func FindHistoricDatumGP(id int, selectCols ...string) *HistoricDatum {
	retobj, err := FindHistoricDatum(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindHistoricDatum retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindHistoricDatum(exec boil.Executor, id int, selectCols ...string) (*HistoricDatum, error) {
	historicDatumObj := &HistoricDatum{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"historic_data\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(historicDatumObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from historic_data")
	}

	return historicDatumObj, nil
}

// FindHistoricDatumP retrieves a single record by ID with an executor, and panics on error.
func FindHistoricDatumP(exec boil.Executor, id int, selectCols ...string) *HistoricDatum {
	retobj, err := FindHistoricDatum(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *HistoricDatum) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *HistoricDatum) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *HistoricDatum) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *HistoricDatum) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no historic_data provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(historicDatumColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	historicDatumInsertCacheMut.RLock()
	cache, cached := historicDatumInsertCache[key]
	historicDatumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			historicDatumColumns,
			historicDatumColumnsWithDefault,
			historicDatumColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(historicDatumType, historicDatumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(historicDatumType, historicDatumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"historic_data\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"historic_data\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into historic_data")
	}

	if !cached {
		historicDatumInsertCacheMut.Lock()
		historicDatumInsertCache[key] = cache
		historicDatumInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single HistoricDatum record. See Update for
// whitelist behavior description.
func (o *HistoricDatum) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single HistoricDatum record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *HistoricDatum) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the HistoricDatum, and panics on error.
// See Update for whitelist behavior description.
func (o *HistoricDatum) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the HistoricDatum.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *HistoricDatum) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	historicDatumUpdateCacheMut.RLock()
	cache, cached := historicDatumUpdateCache[key]
	historicDatumUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			historicDatumColumns,
			historicDatumPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update historic_data, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"historic_data\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, historicDatumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(historicDatumType, historicDatumMapping, append(wl, historicDatumPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update historic_data row")
	}

	if !cached {
		historicDatumUpdateCacheMut.Lock()
		historicDatumUpdateCache[key] = cache
		historicDatumUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q historicDatumQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q historicDatumQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for historic_data")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o HistoricDatumSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o HistoricDatumSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o HistoricDatumSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o HistoricDatumSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), historicDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"historic_data\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, historicDatumPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in historicDatum slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *HistoricDatum) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *HistoricDatum) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *HistoricDatum) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *HistoricDatum) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no historic_data provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(historicDatumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	historicDatumUpsertCacheMut.RLock()
	cache, cached := historicDatumUpsertCache[key]
	historicDatumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			historicDatumColumns,
			historicDatumColumnsWithDefault,
			historicDatumColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			historicDatumColumns,
			historicDatumPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert historic_data, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(historicDatumPrimaryKeyColumns))
			copy(conflict, historicDatumPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"historic_data\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(historicDatumType, historicDatumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(historicDatumType, historicDatumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert historic_data")
	}

	if !cached {
		historicDatumUpsertCacheMut.Lock()
		historicDatumUpsertCache[key] = cache
		historicDatumUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single HistoricDatum record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *HistoricDatum) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single HistoricDatum record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *HistoricDatum) DeleteG() error {
	if o == nil {
		return errors.New("models: no HistoricDatum provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single HistoricDatum record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *HistoricDatum) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single HistoricDatum record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *HistoricDatum) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no HistoricDatum provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), historicDatumPrimaryKeyMapping)
	sql := "DELETE FROM \"historic_data\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from historic_data")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q historicDatumQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q historicDatumQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no historicDatumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from historic_data")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o HistoricDatumSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o HistoricDatumSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no HistoricDatum slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o HistoricDatumSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o HistoricDatumSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no HistoricDatum slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(historicDatumBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), historicDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"historic_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, historicDatumPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from historicDatum slice")
	}

	if len(historicDatumAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *HistoricDatum) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *HistoricDatum) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *HistoricDatum) ReloadG() error {
	if o == nil {
		return errors.New("models: no HistoricDatum provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *HistoricDatum) Reload(exec boil.Executor) error {
	ret, err := FindHistoricDatum(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *HistoricDatumSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *HistoricDatumSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *HistoricDatumSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty HistoricDatumSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *HistoricDatumSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	historicData := HistoricDatumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), historicDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"historic_data\".* FROM \"historic_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, historicDatumPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&historicData)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in HistoricDatumSlice")
	}

	*o = historicData

	return nil
}

// HistoricDatumExists checks if the HistoricDatum row exists.
func HistoricDatumExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"historic_data\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if historic_data exists")
	}

	return exists, nil
}

// HistoricDatumExistsG checks if the HistoricDatum row exists.
func HistoricDatumExistsG(id int) (bool, error) {
	return HistoricDatumExists(boil.GetDB(), id)
}

// HistoricDatumExistsGP checks if the HistoricDatum row exists. Panics on error.
func HistoricDatumExistsGP(id int) bool {
	e, err := HistoricDatumExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// HistoricDatumExistsP checks if the HistoricDatum row exists. Panics on error.
func HistoricDatumExistsP(exec boil.Executor, id int) bool {
	e, err := HistoricDatumExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
